name: flutter_calandar_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 16.4.4+1

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.8
  percent_indicator: ^4.0.1
  expandable: ^5.0.1
  url_launcher: ^6.2.4 #
  syncfusion_flutter_datepicker: ^25.2.4

  share_plus: ^9.0.0
  #share_extend: ^2.0.0
  screenshot: ^3.0.0
  keyboard_actions: ^4.2.0
  nholiday_jp: ^1.0.2
  introduction_screen: ^3.1.12
  shared_preferences: ^2.2.3 #
  toggle_switch: ^2.3.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^4.0.1
  flutter_datetime_picker_plus: ^2.2.0
  flutter_dotenv: ^5.1.0
  flutter_inappwebview: ^6.0.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  flutter_map_animations: ^0.7.0
  rate_my_app: ^2.2.0
  liquid_pull_to_refresh: ^3.0.1

  flutter_localizations:
    sdk: flutter

  sqflite: ^2.3.2 #データベースをいじるパッケージ
  cloud_firestore: ^4.15.5
  http: ^1.1.0 #httpリクエストをするためのパッケージ
  path: ^1.8.3 #
  intl: ^0.19.0
  path_provider: ^2.1.1 #
  flutter_timezone: ^1.0.8
  flutter_local_notifications: ^17.1.2
  device_info_plus: ^10.1.0
  timezone: ^0.9.2
  firebase_core: ^2.27.0
  fl_chart: ^0.68.0
  ulid: ^2.0.0
  #firebase_messaging: ^14.8.2
  emailjs: ^1.3.0
  flutter_app_badger: ^1.5.0
  html: ^0.15.4
  uuid: ^4.4.0
  flutter_colorpicker: ^1.0.3
  home_widget: ^0.6.0
  #workmanager: ^0.5.2
  isar: ^3.1.0
  isar_flutter_libs: ^3.0.0
  collection: ^1.18.0
  receive_sharing_intent: ^1.8.0
  shared_preference_app_group: ^1.1.1
  auto_route: ^8.3.0
  uni_links: ^0.5.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.0
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.2.5
  auto_route_generator: ^8.0.0
  analyzer: ^5.13.0

dependency_overrides:
  flutter_colorpicker:
    git:
      url: https://github.com/mchome/flutter_colorpicker
      ref: master # or 786d04363f587b818ce585d25b9c2bb62de95aba

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/eye_catch/app_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFF422"
  adaptive_icon_foreground: "lib/assets/eye_catch/app_logo.png"


flutter:
  assets:
    - lib/assets/eye_catch/eyecatch.png
    - lib/assets/eye_catch/eyecatch_white.png
    - lib/assets/eye_catch/app_logo.png
    - lib/assets/eye_catch/wase_map_logo.png
    - lib/assets/eye_catch/wase_map_logo_transparent.png

    - lib/assets/calendar_background/ookuma_day.png
    - lib/assets/page_background/sky_wallpaper.png

    - lib/assets/tutorial_images/tag_and_template_button.png
    - lib/assets/tutorial_images/tag_button.png
    - lib/assets/tutorial_images/arbeit_button.png
    - lib/assets/tutorial_images/template_button.png
    - lib/assets/tutorial_images/task_add_button.png
    - lib/assets/tutorial_images/schedule_add_button.png

    - lib/assets/tutorial_images/calendar_introduction.png
    - lib/assets/tutorial_images/task_introduction.png
    - lib/assets/tutorial_images/credits_introduction.png
    - lib/assets/tutorial_images/map_introduction.png
    - lib/assets/tutorial_images/timetable_introduction.png
    - lib/assets/tutorial_images/moodle_introduction.png
    - lib/assets/tutorial_images/more_introduction.png

    - lib/assets/map_images/location_pin.png
    - lib/assets/map_images/location_pin_notempty.png
    - lib/assets/map_images/library_pin.png
    - lib/assets/map_images/food_pin.png

    - lib/assets/map_images/waseda_building_3.png
    - lib/assets/map_images/waseda_building_6.jpg
    - lib/assets/map_images/waseda_building_7.jpg
    - lib/assets/map_images/waseda_building_8.png

    - lib/assets/map_images/waseda_building_10.jpg
    - lib/assets/map_images/waseda_building_11.png
    - lib/assets/map_images/waseda_building_14.png
    - lib/assets/map_images/waseda_building_15.png
    - lib/assets/map_images/waseda_building_16.png
    - lib/assets/map_images/waseda_building_21.png
    - lib/assets/map_images/waseda_building_38.jpg
    - lib/assets/map_images/waseda_building_53.jpg
    - lib/assets/map_images/waseda_building_56.jpg
    - lib/assets/map_images/waseda_building_57.jpg
    - lib/assets/map_images/waseda_building_60.jpg
    - lib/assets/map_images/waseda_building_61.jpg
    - lib/assets/map_images/waseda_building_63.jpg
    - lib/assets/map_images/waseda_central_library.jpg
    - lib/assets/map_images/waseda_toyama_library.jpg
    - lib/assets/map_images/waseda_rikou_library.jpg

    - lib/assets/schedule_share/schedule_backup_upload.png
    - lib/assets/schedule_share/schedule_backup_download.png
    - lib/assets/schedule_share/schedule_broadcast_upload.png
    - lib/assets/schedule_share/schedule_broadcast_download.png
    - .env

    - lib/backend/service/js/auto_login_checkbox.js
    - lib/backend/service/js/get_course_button.js
    - lib/backend/service/js/scroll_controller.js
    - lib/backend/service/js/show_loading_screen.js
    - lib/backend/service/js/hide_loading_screen.js
    - lib/backend/service/js/go_to_myGradePage.js
    - lib/backend/service/js/get_myGrade.js
    - lib/backend/service/js/go_to_myCreditPage.js
    - lib/backend/service/js/get_document.js
    - ios/ShareExtension/GetURL.js

  fonts:
    - family: Noto_Sans_JP
      fonts:
        - asset: lib/assets/fonts/Noto_Sans_JP/static/NotoSansJP-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Noto_Sans_JP/static/NotoSansJP-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/Noto_Sans_JP/static/NotoSansJP-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Noto_Sans_JP/static/NotoSansJP-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Noto_Sans_JP/static/NotoSansJP-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Noto_Sans_JP/static/NotoSansJP-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Noto_Sans_JP/static/NotoSansJP-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Noto_Sans_JP/static/NotoSansJP-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Noto_Sans_JP/static/NotoSansJP-Black.ttf
          weight: 900

  uses-material-design: true
