// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for macos - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX0d9S6NMMaOjjz2--cv4HIy0jtT9o2Fc',
    appId: '1:342079600357:ios:a462571263b2860563460c',
    messagingSenderId: '342079600357',
    projectId: 'wasedule-f719a',
    databaseURL:
        'https://wasedule-f719a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wasedule-f719a.appspot.com',
    iosBundleId: 'com.example.wasedule',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLqp6EL9DnpF8y8CYJ7CdkHW00iDrzh6U',
    appId: '1:342079600357:android:1be5193116e48b5363460c',
    messagingSenderId: '342079600357',
    projectId: 'wasedule-f719a',
    databaseURL:
        'https://wasedule-f719a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wasedule-f719a.appspot.com',
  );
}
