// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5FwyFS8XbF7pxLXQUFeskDnXWuGl9NGM',
    appId: '1:342079600357:web:922ef8dbe3b12d4263460c',
    messagingSenderId: '342079600357',
    projectId: 'wasedule-f719a',
    authDomain: 'wasedule-f719a.firebaseapp.com',
    storageBucket: 'wasedule-f719a.appspot.com',
    measurementId: 'G-YVJ8YPFSLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLqp6EL9DnpF8y8CYJ7CdkHW00iDrzh6U',
    appId: '1:342079600357:android:42cdf983f5a0bed263460c',
    messagingSenderId: '342079600357',
    projectId: 'wasedule-f719a',
    storageBucket: 'wasedule-f719a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX0d9S6NMMaOjjz2--cv4HIy0jtT9o2Fc',
    appId: '1:342079600357:ios:0a6b9a79ac8bd85263460c',
    messagingSenderId: '342079600357',
    projectId: 'wasedule-f719a',
    storageBucket: 'wasedule-f719a.appspot.com',
    iosBundleId: 'com.example.flutterCalendar.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX0d9S6NMMaOjjz2--cv4HIy0jtT9o2Fc',
    appId: '1:342079600357:ios:0a6b9a79ac8bd85263460c',
    messagingSenderId: '342079600357',
    projectId: 'wasedule-f719a',
    storageBucket: 'wasedule-f719a.appspot.com',
    iosBundleId: 'com.example.flutterCalendar.RunnerTests',
  );
}
